version: '3.9'
services:
  db:
    image: 'postgres:latest'
    environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
       - "${DB_PORT}:${DB_PORT}"
    expose:
       - "${DB_PORT}"
    volumes:
      - awstark_db:/var/lib/mysql
volumes:
  awstark_db: {}
