version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "awstark"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vup3ml5s5cxk"
s3_prefix = "awstark"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "awstark"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vup3ml5s5cxk"
s3_prefix = "awstark"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
