AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Awstark API"

Parameters:
  DbUrl:
    Type: String
    Description: Database URL
  ShadowDbUrl:
    Type: String
    Description: Shadow Database URL

Globals:
  Function:
    Timeout: 50
    Tracing: Active
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    MemorySize: 128
    CodeUri: ./
    Environment:
      Variables:
        DB_URL: !Ref DbUrl
        SHADOW_DB_URL: !Ref ShadowDbUrl

  Api:
    TracingEnabled: true

Resources:
  StatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/handlers/status/isUp.default
      Events:
        Status:
          Type: Api
          Properties:
            Path: /status
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: true
        Target: "es2020"
        EntryPoints: 
          - src/handlers/status/isUp.ts
  UserGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/handlers/user/getByEmail.default
      Events:
        Status:
          Type: Api
          Properties:
            Path: /user
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: true
        Target: "es2020"
        EntryPoints: 
          - src/handlers/user/getByEmail.ts
  UserPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/handlers/user/createIfNotExists.default
      Events:
        Status:
          Type: Api
          Properties:
            Path: /user
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: true
        Target: "es2020"
        EntryPoints: 
          - src/handlers/user/createIfNotExists.ts
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Api:
    Description: "awstark API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
