name: Migrate & Deploy CI 

on:
  pull_request:
  push:
    branches: [main]

jobs:
  sam_migrate_build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: aws-actions/setup-sam@v2
    - uses: ./.github/workflows/actions/export-secrets-in-env
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    - uses: ./.github/workflows/actions/migrate-db
      with:
        DB_URL: ${{ env.DB_URL }}
        SHADOW_DB_URL: ${{ env.SHADOW_DB_URL }}
    - run: npm install --omit=dev && npm install esbuild -g && npm run build
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides 'DbUrl=${{ env.DB_URL }} ShadowDbUrl=${{ env.SHADOW_DB_URL }}'
      env:
        CI: true
